apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-bits
  labels:
    app: webapp-bits
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-bits
  template:
    metadata:
      labels:
        app: webapp-bits
    spec:
      containers:
        - name: webapp-bits
          image: mdrhlonedoto/webapp-using-pipeline:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
